### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0xbad)

### ISSUE THREAD

**Issue by michael0952** [johnno1962/InjectionIII#158]
![image](https://user-images.githubusercontent.com/20938747/60875235-ffe66380-a26b-11e9-8706-418d6946c427.png)
💉 *** Compiling /Users/***/Documents/DYS/iOS/***/***/Pages/MinePage/Controller/DYCheckOrderController.swift ***
💉 Loading .dylib ...
objc[88077]: Class _TtC14DaiYanZhenXuan22DYCheckOrderController is implemented in both /Users/***/Library/Developer/CoreSimulator/Devices/5C888264-0B9C-4C38-AEB6-42B31245D135/data/Containers/Bundle/Application/9EB66E35-30A0-490A-9EB7-101D1D00DB69/***.app/*** (0x10f22fb60) and /Users/***/Library/Containers/com.johnholdsworth.InjectionIII/Data/eval101.dylib (0x140b5dae0). One of the two will be used. Which one is undefined.
💉 Loaded .dylib - Ignore any duplicate class warning ^
💉 Injected 'DYCheckOrderController'
I've been injected: <***.DYCheckOrderController: 0x7ff1a41f7e00>
(lldb) 

xcode:10.2.1
swift:5.0.1

some page can inject,but some can't,why?Thanks

**Comment by johnno1962** [comment]
Hi, looks like the problem is with "the sweep" which is used to find active objects of a class that has been injected in an application. You can use INJECTION_BUNDLE_NOTIFICATION instead of an "func injected()" method. Also make sure you don't have any "unowned" objects which breaks the sweep or that you are injecting a file that contains protocols.

**Comment by zx3570** [comment]
It doesn't crash now, thank you
