### ISSUE TITLE
Operation not permitted error

### ISSUE THREAD

**Issue by andermoran** [johnno1962/InjectionIII#177]
This is the error I'm getting with my macOS Objective-C project
```
2019-09-24 09:24:55.507432-0500 temp[60188:51434206] Could not connect: Operation not permitted
💉 Injection loaded but could not connect. Is InjectionIII.app running?
```
My App Delegate has
```Objective-C
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification {
    // Insert code here to initialize your application
    NSBundle *bundle = [NSBundle bundleWithPath:@"/Applications/InjectionIII.app/Contents/Resources/macOSInjection.bundle"];
    [bundle load];
}
```
I'm running this on Xcode 10.3 on macOS Mojave 10.14.5. I have Injectioniii running (I see it in the toolbar) and I have selected my project directory as well. Am I missing something?

**Comment by johnno1962** [comment]
Hi, I have to ask "Is InjectionIII.app running?” and are you using the simulator?

**Comment by zenangst** [comment]
@andermoran do you have sandboxing/hardened runtime enabled for the target? If so, try disabling it to see if the bundle can load properly.

**Comment by andermoran** [comment]
> Hi, I have to ask "Is InjectionIII.app running?” and are you using the simulator?

"I have Injectioniii running" so yes
"macOS Objective-C project" and no because this is a Mac program which runs natively on my own system. No simulator needed

**Comment by johnno1962** [comment]
Ah, I should have mentioned that for a mac App you need to have the sandbox turned off or outgoing socket connections in your capabilities, otherwise the bundle running in the App can’t talk to the InjectionIII app.

**Comment by johnno1962** [comment]
Hi Chris,

Hows Life? I've moved to Italy since we last spoke due to #Brexit.
It's all too stressful to watch a country self-harm to stay around.

I don't know if you've been following: 
https://github.com/johnno1962/InjectionIII/issues/178

but it seems we could be headed for trouble on the latest betas of Catlina.
I can't think of a solution myself. It's all in the issue. Thankfully we had a
competant reporter who's built InjectionIII and been trying a few things for us.

Did you see:
https://github.com/johnno1962/InjectionIII/pull/179

Should be able to merge straight away but I remember you made a chnage
here to stop unnessesary triggers so I'm not sure if it would be a regression.

I'm still settling in here. The awaited overhual of InjectionIII is in the queue
but behind getting myself a home office setup.

Best,

John

**Comment by johnno1962** [comment]
I’ve added a slightly more helpful message for when the connect fails on a macOS app.https://github.com/johnno1962/InjectionIII/pull/181/commits/37f090e636fcb7543a94309ba861207f1194bb0a
