### ISSUE TITLE
Yoga.modulemap not found

### ISSUE THREAD

**Issue by gukemanbu** [johnno1962/InjectionIII#190]
Hi，I write ui interface with [Flexlib](https://github.com/zhenglibao/FlexLib), InjectionIII print error 
'Yoga.modulemap' not found.

**Comment by ziecho** [comment]
💉 *** Compiling /Users/zie/Documents/WeRead/WeReadReactNative/iOS/WeRead/AppDelegate.m ***
💉 *** Re-compilation failed (/Users/zie/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
fatal error: module map file '/Users/zie/Documents/WeRead/WeReadReactNative/iOS/Pods/Headers/Public/yoga/Yoga.modulemap' not found
1 error generated.
 ***

**Comment by maraisf** [comment]
Having a similar issue, not sure if its related
```
 *** Compiling /Users/francoismarais/projects/ios/superbalist-mobile-ios/Superbalist/Superbalist/Targets/iOS/Sources/Components/Authentication/SignUpView.swift ***
💉 *** Re-compilation failed (/Users/francoismarais/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)

<unknown>:0: error: module map file '/Users/francoismarais/projects/ios/superbalist-mobile-ios/Superbalist/../Pods/Headers/Public/protobuf/Protobuf.modulemap' not found
```

**Comment by ziecho** [comment]
> 💉 *** Compiling /Users/zie/Documents/WeRead/WeReadReactNative/iOS/WeRead/AppDelegate.m ***
> 💉 *** Re-compilation failed (/Users/zie/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)
> fatal error: module map file '/Users/zie/Documents/WeRead/WeReadReactNative/iOS/Pods/Headers/Public/yoga/Yoga.modulemap' not found
> 1 error generated.

`Yoga.modulemap` is an alias file, I replaced it with the original file and it worked.

![image](https://user-images.githubusercontent.com/16473618/67696000-06e2de80-f9e1-11e9-95c7-f13701490da2.png)

**Comment by johnno1962** [comment]
Good to hear you’ve found a solution. Look in the script file mentioned in the log:
`/Users/zie/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh` if you’re trying to work out what’s going on.

**Comment by maraisf** [comment]
Just adding this here for context if anyone is having the same issue as I had:

**Error:**
```
*** Compiling /Users/francoismarais/projects/ios/superbalist-mobile-ios/Superbalist/Superbalist/Targets/iOS/Sources/Components/Authentication/SignUpView.swift ***
💉 *** Re-compilation failed (/Users/francoismarais/Library/Containers/com.johnholdsworth.InjectionIII/Data/command.sh)

<unknown>:0: error: module map file '/Users/francoismarais/projects/ios/superbalist-mobile-ios/Superbalist/../Pods/Headers/Public/protobuf/Protobuf.modulemap' not found
```

**Solution:**
As you can see here the `command.sh` script is looking for `protobuf/Protobuf.modulemap`.
I did a search in my project to see if the `Protobuf.modulemap` file exists with
`find superbalist-mobile-ios -name "*f.modulemap*"` 

It found two files:
`superbalist-mobile-ios/Pods/Target Support Files/Protobuf/Protobuf.modulemap`
`superbalist-mobile-ios/Pods/Headers/Public/Protobuf/Protobuf.modulemap`

The second one caused the error. You will notice the actual path is (uppercase P) `Protobuf/Protobuf.modulemap` instead of what the script was looking for (lowercase P) `protobuf/Protobuf.modulemap`

So I just renamed the folder to a lowercase `p` with:
`cd superbalist-mobile-ios/Pods/Headers/Public`
`mv Protobuf protobuf`

**Comment by johnno1962** [comment]
Thanks for feeding this back. Indeed compilations are case sensitive as they run in the simulator.
