### ISSUE TITLE
Could not locate compile command

### ISSUE THREAD

**Issue by 372945980** [johnno1962/InjectionIII#277]
![image](https://user-images.githubusercontent.com/9426832/98455595-d4e88880-21ad-11eb-9745-e527cc95ed4d.png)

**Comment by 372945980** [comment]
Xcode 12.1
iOS 14.1 Simulator
Not using `Whole Module Optimization`。

**Comment by johnno1962** [comment]
Can you try one of the newer releases which may help? https://github.com/johnno1962/InjectionIII/releases

**Comment by sa1dai** [comment]
same problem

**Comment by sa1dai** [comment]
> Can you try one of the newer releases which may help? https://github.com/johnno1962/InjectionIII/releases
Wow! It works on the latest release. Thank you so much!

**Comment by sa1dai** [comment]
@johnno1962 
Reload swift files works as expected, but for storyboard I get: *** Could not locate storyboard compile ***

**Comment by johnno1962** [comment]
If the new version fixes your problem but not for storyboards I'd guess that there is an uppercase/lowercase discrepancy somewhere in your project i.e  file or directory is "Project" in the Xcode project file but on the disk it is actually "project".

**Comment by sa1dai** [comment]
@johnno1962 
I found the bug. The problem is that I created project with whitespace in project name.
Steps to reproduce in XCode 12.2:
1. File -> New -> Project
2. iOS, App -> Next
3. Product Name: `inject test` (whitespace between `inject` and `test` added)
4. Add InjectIII support, go to Main.storyboard add label, change labels name, save file
5.  *** Could not locate storyboard compile *** occurred

I prepared [repository](https://github.com/sa1dai/inject-test) where you can reproduce this.
(but after git clone, you need to rename inject-test to inject test)

**Comment by johnno1962** [comment]
Since you found the problem I was able to find the problem very quickly. I've pushed a very small change to this project if you want to build your own version of InjectionIII and try it out. Thanks for taking the time to raise the issue.
```
    git clone https://github.com/johnno1962/InjectionIII --recurse-submodules
```

**Comment by sa1dai** [comment]
Thank you, I build version for my mac and it works as expected and the error with storyboard is gone
