### ISSUE TITLE
hot reload not found swift file

### ISSUE THREAD

**Issue by BestiOSDev** [johnno1962/InjectionIII#366]
💉 ... to: /Users/dongzb01/Desktop/private_component/Charging/gwwmoduleservice/GWWModuleService/Classes/Modules/WeyServiceHome/Control/GWWServiceHomeControl.swift
💉 Mapped: /Users/dongzb01/Desktop/private_component/Charging/GWWModuleMine/GWWModuleMine/SDKS
💉 ... to: /Users/dongzb01/Desktop/private_component/Charging/gwwmodulemine/GWWModuleMine/SDKS
💉 Compiling /Users/dongzb01/Desktop/private_component/Charging/gwwmoduleservice/GWWModuleService/Classes/Modules/WeyServiceHome/Control/GWWServiceHomeControl.swift
💉 ⚠️ Re-compilation failed (see: /var/folders/91/74j8_x914l98hmhz4vwv5css44wk51/T/com.johnholdsworth.InjectionIII/command.sh)
<unknown>:0: error: primary file '/Users/dongzb01/Desktop/private_component/Charging/gwwmoduleservice/GWWModuleService/Classes/Modules/WeyServiceHome/Control/GWWServiceHomeControl.swift' was not found in file list '/var/folders/91/74j8_x914l98hmhz4vwv5css44wk51/T/com.johnholdsworth.InjectionIII//filelist.txt'

**Comment by johnno1962** [comment]
Hi, This almost certainly a problem with upper/lowercase in a file path i.e. the casing in the filename or path to a module does not agree with the casing on the file system. Grep for GWWServiceHomeControl.swift in the `filelist.txt` it mentions to see what your Xcode project thinks the path should be and either change the project or the range the file. Is this the 3.1.4 App Store version? Otherwise you could try one of the [GitHub releases](https://github.com/johnno1962/InjectionIII/releases) which do not run in the sandbox and are less prone to this problem.
