### ISSUE TITLE
How to set default project and directory

### ISSUE THREAD

**Issue by shridharshetty91** [johnno1962/InjectionIII#421]
Need to choose a project and a directory every single time the developer restarts his machine. Is there a way to set the project and directory automatically, without manual action? If yes please guide me on this.

**Comment by johnno1962** [comment]
Hi, you shouldn't need to set the project every time you restart the InjectionII app as it remembers it unless you have multiple project files in your project root. You can also set this in a environment variable when you run your app: `INJECTION_PROJECT_ROOT`.

**Comment by shridharshetty91** [comment]
Thanks @johnno1962 this is really helpful since we work on multiple projects.

is there a similar variable to specify a folder path for Injectionlll to watch files. We need this because the project file is not in the root directory.

> Hi, you shouldn't need to set the project every time you restart the InjectionII app as it remembers it unless you have multiple project files in your project root. You can also set this in a environment variable when you run your app: `INJECTION_PROJECT_ROOT`.

**Comment by johnno1962** [comment]
That environment variable sets the file watcher path rather than the project file which should be enough to switch between projects. Are you being prompted to select the project afterwards? The alternative is to select your home directory to watch for file changes. This will pick up all source file changes and give you an error if the source file is not in the currently selected project. Which version of the InjectionIII app/HotReloading are you using? If you switch to use the HotReloading project or use one of the more recent binary downloads but quit the app it should all be automatic.

**Comment by shridharshetty91** [comment]
@johnno1962 Yes it's prompting us to select the project every time we run the project because the environment variable is set. We've found 2 ways to solve it. 1) Unselect the environment variable manually from the scheme settings after building the project first time. Or 2) Moving the project file to the root folder. We'll figure out which is a convenient way to solve this. 

It would've been very beneficial if we had an environment variable to specify the project file path similar to the INJECTION_PROJECT_ROOT. 

Please let us know if we have any plans to solve it in the future.

**Comment by johnno1962** [comment]
This is a bit of an edge case (multiple projects) on top of an edge case (without a project file in the project root) so it might require a bit of a rethink for me to find a solution for you. Don't forget to try loading the bundle but not running the InjectionIII app at all with one of the recent GitHub releases. That should "just work". Let me know if it doesn't!

**Comment by johnno1962** [comment]
P.S. if you try to use the injection bundle without the app, don't set env var INJECTION_PROJECT_ROOT.

**Comment by shridharshetty91** [comment]
Yes @johnno1962, looks like all works fine with the latest release without running the app and without setting the environment variable.

Can you please help me understand on the below things listed:

1.  can we just work without the app ever running? If not when do we need to launch it and what is the use of it.
2. We have downloaded the latest app and kept it in application folder. And loading the bundle on app launch. We aren’t using the Swift package. Is it fine?

Thank you so much for your support 🙏

**Comment by johnno1962** [comment]
InjectionIII evolves as I realise new ways it can work. The App is slowly becoming unnecessary except for injection on a device but it is also a good way to make a distribution of the bundles people load. Using the bundles or the HotReloading Swift Package is almost identical now except it's probably easier for people to just load the bundles rather than add/remove the package.
