### ISSUE TITLE
For which paths is it necessary to disable app sandbox in macOS builds?

### ISSUE THREAD

**Issue by samwyndham** [johnno1962/InjectionIII#443]
We are developing an app for macOS:

To use `InjectionIII` with an macOS app we should disable App Sandbox. However, we would prefer not to this as we prefer to keep our debug builds as similar as possible to release, to catch any issues early. Instead we would prefer to use [App Sandbox Temporary Exceptions](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/AppSandboxTemporaryExceptionEntitlements.html) in our entitlements file to only disable app sandbox for certain paths. 

Do you know for which paths app sandbox needs to be disabled? Do you think it would be practical to only disable sand box for those paths?

Thank you and we really appreciate your work!!

**Comment by johnno1962** [comment]
Hi, a better alternative for you might be using the [HotReloading](https://github.com/johnno1962/HotReloading) project instead of loading the `/Applications/InjectionIII.app/Contents/Resources/macOSInjection.bundle` which is one of the paths you'd need to exclude. Most of the work should be done in the `InjectionIII.app` provided you download it. [from GitHub](https://github.com/johnno1962/InjectionIII/releases). You would also need to enable outgoing network connections and turn off the library validation if you have the hardened runtime.

**Comment by samwyndham** [comment]
👍 OK so disabling the app sandbox is only necessary to allow access to `/InjectionIII.app/Contents/Resources/macOSInjection.bundle`? That is good news

**Comment by johnno1962** [comment]
Yes, should be the case (but not for the App Store version of the app)

**Comment by samwyndham** [comment]
I'm not sure it works unfortunately. I enabled App Sandbox in the sample application here https://github.com/johnno1962/SwiftUI-Kit for the macOS app and added some catch all path exception:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.files.user-selected.read-only</key>
	<true/>
	<key>com.apple.security.network.client</key>
	<true/>
	<key>com.apple.security.temporary-exception.files.absolute-path.read-write</key>
	<array>
		<string>/</string>
	</array>
</dict>
</plist>
```

But I get the following alert:

![Screenshot 2023-04-18 at 15 39 42](https://user-images.githubusercontent.com/3738412/232797044-22022cd1-abff-4a03-bd7f-f583a193e8f0.png)

Along with errors such as:

```
'/private/var/folders/f9/rwl2xcqd2457nddrkdkbf_nh0000gn/T/lilsoftware-Kit-Mac/eval101.dylib' not valid for use in process: library load disallowed by system policy),
```

**Comment by johnno1962** [comment]
I can't replicate this end and that it says the .dylib was written by your app implies you're using the App Store version of InjectionIII.app or built your own version without turning off the sandbox. Is that possible? You need to use one of the GitHub downloads https://github.com/johnno1962/InjectionIII/releases.

**Comment by samwyndham** [comment]
Interesting. I'll take a further look at this. I'm on macOS Ventura 13.1. I'm not using the app store version but am running the latest version from  https://github.com/johnno1962/InjectionIII/releases. I did have the app store version installed once though. Furthermore in this case I thought I was using [HotReloading](https://github.com/johnno1962/HotReloading) instead of the application

**Comment by johnno1962** [comment]
It's complicated, there are many configurations with the Injection codebase and injecting macOS is more complicated with the sandbox and library validation which affects code signing requirements. The one you probably want is using the downloaded app, loading it's bundle and connecting to the app to do the compilation and preparation of the dynamic library. Don't forget to enable outgoing network connection entitlement. You can use the HotReloading project instead of the bundle but loading the bundle which is HotReloading pre-packaged is probably easiest unless you are working on injection itself.
