### ISSUE TITLE
Re-compilation failed, error: cannot find type '*' in scope

### ISSUE THREAD

**Issue by lockieluke** [johnno1962/InjectionIII#460]
![image](https://github.com/johnno1962/InjectionIII/assets/25424409/1087f203-03cc-4807-a374-fa29b2f55d26)

This randomly happens with different files
![image](https://github.com/johnno1962/InjectionIII/assets/25424409/a36e8ccc-db14-457f-bc8e-fa3beb770fad)
we are currently at 114 source files

**Comment by johnno1962** [comment]
Hi, which version of InjectionIII, Xcode and macOS are you using? Can you try moving the project out of the ~/Documents folder. This might sound like a long shot but it has caused problems in the past.

**Comment by lockieluke** [comment]
yes i am indeed adding files to the project

**Comment by johnno1962** [comment]
Normally I'd expect the compilation to re-prase the build logs of your project and retry when it fails like this. I wonder if you're having an issue where the wrong build logs are being used such as in this issue https://github.com/johnno1962/InjectionIII/issues/393#issuecomment-1722018776. Can you try the latest 4.7.4 build and see if it resolves the problem? Otherwise all you can do is rebuild your project, close and re-open it to reset the build logs, remove the cache files and retry when you change the files in a project.
